name: LinkedList
author: thinkphp
current: v1.0
category: utilities
tags: [linkedlist, list, linked, datastructures, collections]
docs: https://github.com/thinkphp/LinkedList/blob/master/Docs/LinkedList.md 
demo: http://thinkphp.github.com/LinkedList